In [2]:
import numpy as np

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.ones(10) * 4

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [7]:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [9]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
arr[2,1]

12

In [11]:
arr[-1]

array([21, 22, 23, 24, 25])

In [12]:
arr[:3, :3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [13]:
arr[1:4, 1:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [14]:
arr[3:, :3]

array([[16, 17, 18],
       [21, 22, 23]])

In [15]:
randarr = np.random.rand(20)
randarr

array([0.31113804, 0.80142918, 0.99812997, 0.00730427, 0.68286534,
       0.93949038, 0.41939412, 0.18962785, 0.85630639, 0.02731526,
       0.10726499, 0.96167823, 0.55559707, 0.70195254, 0.4586885 ,
       0.92826504, 0.44027953, 0.17399255, 0.81133053, 0.31999365])

In [17]:
max(randarr)

0.9981299682500446

In [18]:
randarr.argmax()

2

In [19]:
randarr.min()

0.007304269425011278

In [20]:
randarr.argmin()

3

In [21]:
randarr.dtype

dtype('float64')

In [23]:
bandymas = np.arange(1,101)
bandymas

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [24]:
bandymas[bandymas > 90]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [25]:
bandymas[bandymas % 7 == 0]

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [26]:
np.linspace(0.025,1,40).reshape(5,8)

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

In [27]:
matrica = np.arange(2,1000)
res = matrica[(matrica ** 0.5) % 1 == 0].reshape(6,5)
res

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676],
       [729, 784, 841, 900, 961]])

Sukurkite vektorių iš sveikų sk. nuo 1 iki 100. Priskirkite kintamąjam.

Sukurkite Python funkciją, kuri tikrina ar parametruose įvestas sk. yra pirminis. Jeigu pirminis, grąžina True, jei ne, False.

NumPy nevisada supranta įprastą Python kodą su range'ais ir list'ais, todėl sukurtą funkciją teks vektorizuoti taip : nauja_funkcija = np.vectorize(jūsų_funkcija) .

Kadangi sąlygos reikšmių traukimui yra bool reikšmės, pabandykite vietoje sąlygos įdėti savo vektorizuotą funkciją, ir taip išrinkti pirminius skaičius iš savo vektoriaus

In [28]:
testlist = np.arange(1,101)
def is_prime(number):
    for i in range(2, number):
        if number % i == 0:
            return False
    return True
vis_prime = np.vectorize(is_prime)
testlist[vis_prime(testlist)]

array([ 1,  2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53,
       59, 61, 67, 71, 73, 79, 83, 89, 97])